amlak2/urls.py
# from django.conf.urls.defaults import *
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url




urlpatterns = [
    path('admin/', admin.site.urls),
   # path('api-auth/', include('rest_framework.urls')),
    path('core/', include('core.urls',namespace='core')),
    path('report_builder/', include('report_builder.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/urls.py
from django.urls import path,include
# from .views import UnitForm,MelkForm, UserLoginForm, UserRegisterForm
from .views import *
# from django.conf import settings
#from .views import MapWidgetListView, PointFieldGoogleWidgetView, PointFieldGoogleStaticWidgetView, PointFieldGoogleStaticOverlayWidgetView
app_name = 'core'

urlpatterns = [

        path('', index_view, name='index'),
        path('uploadcsv/', upload_csv, name='upload_csv'),
        path('downloadcsv/', download_csv, name='download_csv'),
        # path('ajax/load_cities/', load_cities, name='load_cities'),
        #path('logout/', Signout, name='logout'),
        path('login/', login_view, name='login'),
        path('logout/', logout_view, name='logout'),
        path('register/', Register_view, name='register'),
        path('unit/', UnitCreateView, name='unit_create'),
        #path('<int:id>/', UnitDetailView, name='detail'),
        path('<int:id>/update/', UnitUpdateView, name='unit_update'),
        path('<int:id>/delete/', UnitDeleteView, name='unit_delete'),
        path('melk/', MelkCreateView, name='melk_insert'),
        path('update/', MelkUpdateView, name='melk_update'),
        # path('search/', MelkFilterView, name='melk_search'),
        path('upload/', Upload_view, name='upload'),
        path('<int:id>/melkdelete/', MelkDeleteView, name='melk_delete'),
        path('brand/<int:id>', all_json_models),
        
]

core/models.py
import django.db
import ckeditor
import django_filters

from django_jalali.db import models as jmodels
from django.urls import reverse
from django.contrib.gis.db import models
from ckeditor.fields import RichTextField
#from ckeditor_uploader.fields import RichTextUploadField
from django.contrib.gis.geos import Point
from location_field.models.spatial import LocationField
# from django.contrib.gis.db.models import PointField
from location_field.models.plain import PlainLocationField

# from location_field.models.spatial import LocationField
# from django.contrib.gis.gdal.geometries import Point
from django_filters.rest_framework.filters import ModelChoiceFilter
from django.forms import ModelChoiceField
# from djmoney.models.fields import MoneyField




# class Location( models.Model ):
#     location_point = models.PointField( null=True, blank=True )
# # class Location(models.Model):
# #         location_point = LocationField(based_fields=['city'], zoom=7, default=Point(51.67, 32.65), null=True, blank=True)

#     class Meta:
#         verbose_name = 'موقعیت'
#         verbose_name_plural = 'موقعیت جغرافیایی'

class Ostan(django.db.models.Model):
    name = django.db.models.CharField(max_length=20, verbose_name="استان")
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'استان'
        verbose_name_plural = 'استان ها'

class City(django.db.models.Model):
    ostan = django.db.models.ForeignKey(Ostan, on_delete=models.SET_NULL, null=True, verbose_name ='استان')
    name = django.db.models.CharField(max_length=50,verbose_name ='شهر')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'شهر'
        verbose_name_plural = 'شهرستان'
        
# class Rosta(django.db.models.Model):
#     city = django.db.models.ForeignKey(City,blank=True, on_delete=models.SET_NULL, null=True,verbose_name ='شهرستان')
#     name = django.db.models.CharField(max_length=50, verbose_name="روستا")
#     def __str__(self):
#         return self.name
#     class Meta:
#         verbose_name = 'روستا'
#         verbose_name_plural = 'دهستان'

class Unit(django.db.models.Model):
    u_code = django.db.models.CharField(max_length=40, verbose_name="کد منطقه")
    u_name = django.db.models.CharField(max_length=50, verbose_name="نام منطقه")
    def __str__(self):
        return (self.u_name)
    def get_absolute_url(self):
        return reverse("core:unit_create", kwargs={})
        #return reverse("core:unit_update", kwargs={"id": self.id})
    class Meta:
        verbose_name = 'منطقه'
        verbose_name_plural = 'مناطق'

class Melk(django.db.models.Model):
    melk_name = django.db.models.CharField(max_length=100, verbose_name="نام ملک")
    khayer_name = django.db.models.CharField(max_length=100, verbose_name="نام واگذارکننده")
    sanad_asli = django.db.models.CharField(max_length=20, verbose_name="شماره سند اصلی")
    sanad_farye = django.db.models.CharField(max_length=20, verbose_name="شماره سند فرعی")
    CHOICES1 =(
            ('عادی','عادی'),
            ('قطعی دفترچه ای','قطعی دفترچه ای'),
            ('قطعی غیرمنقول','قطعی غیرمنقول'),
            ('صلح نامه','صلح نامه'),
            ('وقف نامه','وقف نامه'),
            ('ابتیاعی','ابتیاعی')
            )
    sanad_type = django.db.models.CharField(choices=CHOICES1, max_length=50, verbose_name="نوع سند واگذاری")
    CHOICES4 = (
            ('در حال بهره برداری', 'درحال بهره برداری'),
            ('کشاورزی', 'کشاورزی'),
            ('زمین', 'زمین')

        )
    melk_state = django.db.models.CharField(choices=CHOICES4,max_length=50, verbose_name="وضعیت کنونی ملک")
    CHOICES3 = (
            ('آموزش و پرورش', ' آموزش و پرورش'),
            ('اوقاف', 'اوقاف'),
            ('دولت', 'دولت'),
            ('آستانه', 'آستانه'),
            ('غیره', 'غیره'),

        )
    melk_motavali = django.db.models.CharField(choices=CHOICES3,max_length=100, verbose_name="متولی ملک")
    CHOICES2 = (
            ('آموزشی', 'آموزشی'),
            ('اداری', 'اداری'),
            ('مسکونی', 'مسکونی'),
            ('غیره', 'غیره')

        )
    melk_karbari = django.db.models.CharField(choices=CHOICES2,max_length=50, verbose_name="نوع کاربری ملک")
    melk_year = django.db.models.DateField(verbose_name="سال واگذاری ملک")
    melk_arseh = django.db.models.CharField(max_length=10, verbose_name="عرصه ملک")
    melk_price = django.db.models.CharField(max_length=20, verbose_name="ارزش ریالی ملک")
    melk_ayan = django.db.models.CharField(max_length=10, verbose_name="اعیان ملک")
    melk_comment = RichTextField(max_length=1000, verbose_name="توضیحات سند ملک")
    melk_pic = django.db.models.FileField(blank=True, null=True, verbose_name="تصویر سند ملک")
    ostan = django.db.models.ForeignKey(Ostan, on_delete=models.SET_NULL, null=True, verbose_name="استان")
    city = django.db.models.ForeignKey(City, on_delete=models.SET_NULL, null=True,blank=True, verbose_name="شهرستان")
    rosta = django.db.models.CharField(max_length=30,verbose_name="روستا") 
    post_code = django.db.models.CharField(max_length=10, verbose_name="کدپستی")
    address = django.db.models.CharField(max_length=200, verbose_name="آدرس ملک")
    #melk_gps = django.db.models.CharField(max_length=100, verbose_name="موقعیت جغرافیایی ملک")
    melk_gps = django.db.models.CharField(max_length=10, verbose_name="موقعیت جغرافیایی ملک")
    latitude = models.DecimalField(max_digits=20, decimal_places=17, null=True, verbose_name="طول جغرافیایی")
    longitude = models.DecimalField(max_digits=20, decimal_places=17, null=True, verbose_name="عرض جغرافیایی")
    
    class Meta:
        verbose_name = 'ملک'
        verbose_name_plural = 'املاک'
        ordering = ['sanad_asli']
    def __str__(self):
        return self.melk_name
    
    def get_absolute_url(self):
        return reverse("core:melk_insert", kwargs={})

    def __repr__(self):
        return str(self.melk_year)

core/views.py
import django.shortcuts
import csv,io, json
import logging
from django.urls import reverse
#from .filters import MelkFilter
from django.http import HttpResponseRedirect,HttpResponse

from django.shortcuts import render
#from .forms import UploadFileForm
# from somewhere import handle_uploaded_file
from django.http import JsonResponse, request
from .models import Melk, Unit, City, Ostan
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from .forms import UnitForm, MelkForm, UserLoginForm, UserRegisterForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)

from click import prompt
from django.core import serializers
from jalali_date import datetime2jalali, date2jalali

# def my_view(request):
# 	jalali_join = datetime2jalali(request.user.date_joined).strftime('%y/%m/%d _ %H:%M:%S')

# @login_required
def index_view(request):
    post = Unit.objects.all()
    form = UnitForm()
    return django.shortcuts.render(request, 'core/index.html', {"post":post})

def login_view(request):
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request,user)
        if next:
            return django.shortcuts.redirect(next)
        return django.shortcuts.redirect('/core')
    context = {
        'form' : form,
        }
    return django.shortcuts.render(request, 'core/login.html', context)

def Register_view(request):
    next = request.GET.get('next')
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password)
        user.save()
        messages.add_message(request, messages.SUCCESS, " ثبت نام با موفقیت انجام شد.")
        new_user = authenticate(username=user.username, password=password)
        login(request,new_user)
        if next:
            return django.shortcuts.redirect(next)
        return django.shortcuts.redirect('/core/register')
    context = {
        'form' : form,
        }
    return django.shortcuts.render(request, 'core/signup1.html', context)

def logout_view(request):
    logout(request)
    return django.shortcuts.redirect('/core/login')

def UnitCreateView(request):
    form = UnitForm(request.POST or None)
    post = Unit.objects.all()
    ucode = request.POST.get('u_code')
    
    if ucode !='' or None:
        if post.filter(u_code = ucode):
            messages.success(request,"منطقه مورد نظر قبلا ثبت شده است")
        elif form.is_valid():
            postss= form.save()
            messages.success(request,"ثبت با موفقیت انجام شد...")
            form = UnitForm()
            return django.shortcuts.HttpResponseRedirect(postss.get_absolute_url())
    
   
    # unit_list = Unit.objects.all()
    # page = request.GET.get('page', 1)
    # paginator1 = Paginator(unit_list, 10 ) # Show 5 unit per page  
    
    # try:
    #     posts=paginator1.page(page)
    # except PageNotAnInteger:     
    #     posts=paginator1.page(1)
    # except(EmptyPage):
    #    posts = paginator1.page(paginator1.num_pages)

    context = {
      "post":post,
      "form":form,
    #   "posts":posts, 
    }
    return django.shortcuts.render(request, 'core/unit_edit.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
def UnitUpdateView(request, id):
   
    postt = django.shortcuts.get_object_or_404(Unit, id=id)
    post = Unit.objects.all()
    
    form = UnitForm(request.POST or None, instance=postt)
    if form.is_valid():
        form.save()
        messages.success(request,"ویرایش با موفقیت انجام شد...")
        return django.shortcuts.HttpResponseRedirect(postt.get_absolute_url())
    # unit_list = Unit.objects.all()
    # paginator = Paginator(unit_list, 10 ) # Show 5 unit per page
    # try:
    #     page = int(request.GET.get('page', '1' ))
    # except:
    #     page = 1
    # try:
    #     posts=paginator.page(page)
    # except(EmptyPage):
    #    posts = paginator.page(paginator.num_pages)
    context = {
      "postt":postt,
      "post":post,
      "form":form,
    #   "posts":posts,   
    }
    return django.shortcuts.render(request, 'core/unit_update.html', context)
    

def UnitDeleteView(request, id):
    post = django.shortcuts.get_object_or_404(Unit, id=id)
    if request.method == "POST":
       post.delete()
       return django.shortcuts.HttpResponseRedirect(post.get_absolute_url())
    return django.shortcuts.render (request, "core/confirm_unit.html", {"post":post})

def Upload_view(request):
    #post = get_object_or_404(Melk)
    # if form.is_valid():
    #     form.save()
    #     messages.success(request,"ثبت با موفقیت انجام شد...")
    #     return HttpResponseRedirect(form.get_absolute_url())
    # if request.method == "POST":
    #    post.save()
    #    messages.success(request,"ثبت با موفقیت انجام شد...")
    #    return HttpResponseRedirect(post.get_absolute_url())
    return django.shortcuts.render (request, "core/upload.html")



def MelkCreateView(request):
    # jalali_join = datetime2jalali(request.user.date_joined).strftime('%y/%m/%d _ %H:%M:%S')
    
    form = MelkForm(request.POST or None, request.FILES or None)
    post = Melk.objects.all()
    sanadasli = request.POST.get('sanad_asli')
    
    if sanadasli !='' or None:
        
        
        if post.filter(sanad_asli = sanadasli):
            messages.success(request,"این سند قبلا ثبت شده است")
        
        elif form.is_valid():
            
            post = form.save()
            messages.success(request, "ثبت با موفقیت انجام شد...")
            return django.shortcuts.HttpResponseRedirect(post.get_absolute_url())
        else :
            messages.error(request, "فرم قانونی نیست")
    # ostan_id = request.GET.get('ostanid')
    # cities = City.objects.filter(ostan_id=ostan_id).order_by('name')
    # city_id = request.GET.get('cityid')
    
    
    context = {
      "form":form,
      "post":post,
    }
    return django.shortcuts.render (request, 'core/melk_insert1.html', context)


def is_valid_queryparam(param):
   return param != '' and param is not None

def MelkUpdateView(request):
    post = Melk.objects.all()

    melksearch1 = request.POST.get('melksearch')
    # post = MelkFilter(request.GET, queryset=Melk.objects.all())
    
    if is_valid_queryparam(melksearch1):
       post = post.filter(melk_name = melksearch1)
   
    # paginator = Paginator(post, 15 ) # Show 5 unit per page
    # try:
    #     page = int(request.GET.get('page', '1' ))
    # except:
    #     page = 1
    # try:
    #     posts=paginator.page(page)
    # except(EmptyPage):
    #    posts = paginator.page(paginator.num_pages)
    ostan_id = request.GET.get('ostan')
    cities = City.objects.filter(ostan_id=ostan_id).order_by('name')
    city_id = request.GET.get('city')
    # rosta = Rosta.objects.filter(city_id=city_id).order_by('name')
    context = {
      "post":post,  
      "cities" :cities,
    #   "rostas":rosta,
    #   "posts":posts,   
    }

    return django.shortcuts.render (request, 'core/melk_update.html', context) 
    
   

def MelkDeleteView(request, id):
    post = django.shortcuts.get_object_or_404(Melk, id=id)
    if request.method == "POST":
       post.delete()
       return django.shortcuts.HttpResponseRedirect(post.get_absolute_url())
    return django.shortcuts.render (request, "core/confirm_melk.html", {"post":post})

def upload_csv(request):
    template = "core\csvupload.html"
    prompt= {'order':'فایل شما دارای کدمنطقه و نام منطقه باشد.'}
    if request.method=="GET":
       return render(request, template, prompt)
    csv_file = request.FILES['file']

    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'این فایل csv نیست')
    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=',',quotechar="|"):
        _,created = City.objects.update_or_create(
            id=column[0],
            name=column[1],
            ostan_id=column[2],
        )
    context={}
    return render(request,template,context)

def download_csv(request):
    items = Unit.objects.all()

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="unit.csv"'
    writer = csv.writer(response,delimiter=',')
    writer.writerow(['u_code','u_name'])

    for obj in items:
        writer.writerow([obj.u_code,obj.u_name])
    return response
    


def all_json_models(request, id):
    current_brand = Ostan.objects.get(code=id)
    models = City.objects.all().filter(brand=current_brand)
    json_models = serializers.serialize("json", models)
    return HttpResponse(json_models, mimetype="application/javascript")

core/templates/core/confirm_melk.html
{% extends "core/index.html" %}
{%block content%}

<form action="{% url 'core:melk_delete' post.id %}" method='POST' > 
    {% csrf_token %}
    <h1> آیا شما مطمئنید می خواهید "{{post.melk_name}}" را پاک کنید ...</h1>
    <p>
    <input name="" id="" class="btn btn-primary" type="submit" value="بله"/>
    <a href="{% url 'core:melk_update'  %}"> خیر</a>
    </p>
</form>

{% endblock %}

core/templates/core/login.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
  <head>
    <title>صفحه ورود به سایت</title>
    <meta charset="utf-8">
    <meta content="ie=edge" http-equiv="x-ua-compatible">
    <meta content="template language" name="keywords">
    <meta content="Tamerlan Soziev" name="author">
    <meta content="Admin dashboard html template" name="description">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <link href="favicon.png" rel="shortcut icon">
    <link href="apple-touch-icon.png" rel="apple-touch-icon">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet" type="text/css">
    <link href="{% static '/bower_components/select2/dist/css/select2.min.css'%}" rel="stylesheet">
    <link href="{% static '/bower_components/bootstrap-daterangepicker/daterangepicker.css'%}" rel="stylesheet">
    <link href="{% static '/bower_components/dropzone/dist/dropzone.css'%}" rel="stylesheet">
    <link href="{% static '/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static '/bower_components/fullcalendar/dist/fullcalendar.min.css'%}" rel="stylesheet">
    <link href="{% static '/bower_components/perfect-scrollbar/css/perfect-scrollbar.min.css'%}" rel="stylesheet">
    <link href="{% static '/bower_components/slick-carousel/slick/slick.css'%}" rel="stylesheet">
    <link href="{% static 'css/main.css'%}" rel="stylesheet">
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css' rel='stylesheet' />
  </head>
  <body class="auth-wrapper">
  <div class="all-wrapper menu-side with-pattern">
      <div class="auth-box-w">
        <div class="logo-w">
          <a href="{% url 'core:login'%}"><img alt="" src="{% static 'img/logo-big.png' %}"></a>
        </div>
        <h4 class="auth-header">
          وارد شوید
        </h4>
        

        <form method="POST"  >
          {% csrf_token %}
          <div class="form-group">
            <label for="">نام کاربری</label>
              {{form.username}}
            
            <div class="pre-icon os-icon os-icon-user-male-circle"></div>
          </div>
          <div class="form-group">
            <label for="">کلمه عبور</label>
              {{form.password}}

            <div class="pre-icon os-icon os-icon-fingerprint"></div>
          </div>
          <div class="buttons-w">
            <button class="btn btn-primary">وارد شوید</button>
            {% comment %} <div class="form-check-inline">
              <label class="form-check-label">
              <input class="form-check-input" type="checkbox">مرا به خاطر بسپار...</label>
            </div> {% endcomment %}
          </div>
        </form>
      </div>
    </div>
 
</body>
</html>

core/templates/core/melk_update.html
{% extends 'core/index.html' %}
{%block content%}
{% load static %}
{% load bootstrap4 %}
{%load crispy_forms_tags%}

<div class="col-lg-12">
                       
                        
                                <div class="element-wrapper">
                                    <div class="element-box">
                                        <h5 class="form-header">
                                        لیست املاک
                                        </h5>
                                        
                                        <div class="element-box-tp">
                                        <!--------------------
                                        START - Controls Above Table
                                        -------------------->
                                        <form method= "POST" action=".">
                                        {% csrf_token %}
                                            <div class="controls-above-table">
                                                <div class="row">
                                                    <div class="col-sm-3">                                                    
                                                        <div class="element-search autosuggest-search-activator ssg-icon">                                                        
                                                            <input name="melksearch" id="myInput" class="form-control form-control-sm rounded bright" placeholder="جستجو" type="search" />
                                                        
                                                        </div>
                                                    
                                                    </div>
                                                      <button type="submit" class="btn btn-primary ">جستجو</button>
                                                </div>
                                           
                                            </div> 
                                        </form>  
                                        <!--------------------
                                        END - Controls Above Table
                                        -------------------->
                                        <div class="table-responsive">
                                        {% comment %} id="example" class="table table-striped table-bordered" style="width:100%" {% endcomment %}
                                            {% comment %} <table class="table table-bordered table-lg table-v1 table-striped" > {% endcomment %}
                                            <table id="example" class="table table-bordered table-lg table-v2 table-striped" width=100% >
                                            <thead>
                                                    <tr>
                                                    <th>
                                                        <h6>
                                                        کد ملک
                                                        </h6>
                                                    </th>
                                                    <th>
                                                        <h6>
                                                        نام ملک
                                                        </h6>
                                                    </th>
                                                    <th>
                                                        <h6>
                                                      متولی ملک
                                                        </h6>
                                                    </th>
                                                    <th>
                                                        <h6>
                                                        تاریخ سند
                                                        </h6>
                                                    </th>
                                                    <th>
                                                        <h6>
                                                       کاربری ملک
                                                        </h6>
                                                    </th>
                                                    <th>
                                                        <h6>
                                                        شهرستان
                                                        </h6>
                                                    </th>
                                                    <th>
                                                        <h6>
                                                        آدرس
                                                        </h6>
                                                    </th>
                                                    <th>
                                                        <h6>
                                                        عملیات
                                                        </h6>
                                                    </th>

                                                    </tr>
                                            </thead>
                                            <tbody id="myTable" >     
                                                
                                               
                                                     
                                                        {%for Sabt in post %}
                                                        
                                                            <tr>
                                                                <td>
                                                                    {{ Sabt.sanad_asli }}
                                                                </td>                    
                                                                <td>
                                                                    {{ Sabt.melk_name }}
                                                                </td>
                                                                <td>
                                                                    {{ Sabt.melk_motavali }}
                                                                </td>  
                                                                <td>
                                                                    {{ Sabt.melk_year }}
                                                                </td>                    
                                                                <td>
                                                                    {{ Sabt.melk_karbari }}
                                                                </td>
                                                                <td>
                                                                    {{ Sabt.city }}
                                                                </td>                                      
                                                                <td>
                                                                    {{ Sabt.address }}
                                                                </td>
                                                                <td class="row-actions">
                                                                    <a href="{% url 'core:melk_update'  %}"><i class="os-icon os-icon-ui-49"></i></a>
                                                                    <a class="danger" href="{% url 'core:melk_delete' Sabt.id %}"><i class="os-icon os-icon-ui-15"></i></a>
                                                                </td>                      
                                                            
                                                            </tr>
                                                        {% endfor %}                                                 
                                                       
                                                                                                       
                                            </tbody>
                                           
                                            </table>
                                          
                                        </div> 
                                        
                                            {%if posts.has_other_pages %}
                                                <ul class="pagination">
                                                    {% if posts.has_previous %}
                                                        <li class="page-item">
                                                        <a href="?page={{posts.previous_page_number}}" class="page-link">قبلی</a>
                                                        </li>
                                                    {% else %}
                                                        <li class="page-item disabled"><span>قبلی</span></li>
                                                    {% endif %}
                                                    {% for p in posts.paginator.page_range %} 
                                                        {% if posts.number == p %}
                                                            <li class="page-item active">
                                                            <a href="?page={{p}}" class="page-link">{{p}}</a>
                                                            </li>
                                                        {% else %}
                                                            <li class="page-item">
                                                                <a href="?page={{p}}" class="page-link">{{p}}</a>
                                                            </li>
                                                        {%endif%} 
                                                    {%endfor%}
                                                    {% if posts.has_next %}
                                                        <li class="page-item">
                                                            <a href="?page={{posts.next_page_number}}" class="page-link">بعدی</a>
                                                        </li>
                                                    {%else%}
                                                        <li class="page-item disabled"><span>بعدی</span></li>
                                                    
                                                    {%endif%}                                        
                                                </ul>
                                            {%endif%}
                                        </div>                                                         
                                    </div>
                                   
                                </div> 
                        
                  
{% endblock %}